spring:
  datasource:
    url: jdbc:h2:file:~/proyectoh2
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      
server:
  error:
    include-message: always